apiVersion: cloudnativetoolkit.dev/v1alpha1
kind: Catalog
categories:
  - category: custom_module
    categoryName: custom_module
    selection: multiple
    modules:
      - cloudProvider: ""
        softwareProvider: ""
        type: gitops
        id: github.com/thomassuedbroecker/gitops-terraform-guestbook
        group: ""
        displayName: gitops-terraform-guestbook
        name: gitops-terraform-guestbook
        description: "That module will add a new Argo CD config to deploy the guestbook application"
        tags:
          - tools
          - gitops
        versions:
          - platforms:
              - kubernetes
              - ocp3
              - ocp4
            dependencies:
              - id: gitops
                refs:
                  - source: github.com/cloud-native-toolkit/terraform-tools-gitops.git
                    version: '>= 1.1.0'
              - id: namespace
                refs:
                  - source: github.com/cloud-native-toolkit/terraform-gitops-namespace.git
                    version: '>= 1.0.0'
            variables:
              - name: gitops_config
                description: Config information regarding the gitops repo structure
                moduleRef:
                  id: gitops
                  output: gitops_config
              - name: git_credentials
                description: The credentials for the gitops repo(s)
                sensitive: true
                moduleRef:
                  id: gitops
                  output: git_credentials
              - name: namespace
                type: string
                description: The namespace where the application should be deployed
                moduleRef:
                  id: namespace
                  output: name
              - name: kubeseal_cert
                type: string
                description: The certificate/public key used to encrypt the sealed secrets
                default: ""
                moduleRef:
                  id: gitops
                  output: sealed_secrets_cert
              - name: server_name
                type: string
                description: The name of the server
                default: default
                moduleRef:
                  id: gitops
                  output: server_name
            version: v0.0.1
            outputs:
              - name: name
                description: The name of the module
              - name: branch
                description: The branch where the module config has been placed
              - name: namespace
                description: The namespace where the module will be deployed
              - name: server_name
                description: The server where the module will be deployed
              - name: layer
                description: The layer where the module is deployed
              - name: type
                description: The type of module where the module is deployed
