apiVersion: cloudnativetoolkit.dev/v1alpha1
kind: Catalog
categories:
  - category: custom_module
    categoryName: custom_module
    selection: multiple
    modules:
      - cloudProvider: ""
        softwareProvider: ""
        id: github.com/thomassuedbroecker/gitops-terraform-guestbook
        group: ""
        displayName: gitops-terraform-guestbook
        type: gitops
        name: gitops-terraform-guestbook
        type: gitops
        description: "That module will add a new Argo CD config to deploy the guestbook application"
        tags:
          - tools
          - gitops
        versions:
          - platforms:
            - kubernetes
            - ocp3
            - ocp4
        dependencies:
          - id: gitops
            refs:
              - source: github.com/cloud-native-toolkit/terraform-tools-gitops.git
               version: ">= 1.1.0"
          - id: namespace
            refs:
              - source: github.com/cloud-native-toolkit/terraform-gitops-namespace.git
                version: ">= 1.0.0"
        variables:
          - name: gitops_config
            moduleRef:
              id: gitops
              output: gitops_config
          - name: git_credentials
            moduleRef:
              id: gitops
              output: git_credentials
          - name: server_name
            moduleRef:
              id: gitops
              output: server_name
          - name: namespace
            moduleRef:
              id: namespace
              output: name
          - name: kubeseal_cert
            moduleRef:
              id: gitops
              output: sealed_secrets_cert
   